version: "3.7"

services:      
    Seleniumhub:
      container_name: Selenium-hub-compose
      image: selenium/hub
      ports: 
        - 4444:4444

    Firefoxnode:
      container_name: Selenium-Firefox-compose
      image: selenium/node-firefox-debug
      ports: 
        - 4577:5900
      depends_on:
        - Seleniumhub
      environment:
        HUB_PORT_4444_TCP_ADDR: Seleniumhub
        HUB_PORT_4444_TCP_PORT: 4444
        NODE_MAX_SESSION: 2
        NODE_MAX_INSTANCES: 2
      links:
        - Seleniumhub
   

    Chromenode:
      container_name: Selenium-Chrome-compose
      image: selenium/node-chrome-debug
      ports: 
        - 4578:5900
      depends_on:
        - Seleniumhub
      environment:
        HUB_PORT_4444_TCP_ADDR: Seleniumhub
        HUB_PORT_4444_TCP_PORT: 4444
        NODE_MAX_SESSION: 2
        NODE_MAX_INSTANCES: 2
      links:
        - Seleniumhub
     